name: Build NiteWorksSite

env:
  # set this to the dot net version to use: 
  DOTNET_VERSION: '3.1.x'

on:
  push:
    branches: [ main ]
    paths:
    - 'NiteWorksSite/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'NiteWorksSite/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
        
    - name: Install dependencies
      run: dotnet restore NiteWorksSite/NiteWorks/NiteWorks.csproj

    - name: Build
      run: dotnet build NiteWorksSite/NiteWorks/NiteWorks.csproj --configuration Release --no-restore
